name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
        npm run copy-artifacts

    - name: Push artifacts to repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'build/*'
        destination_repo: 'TokenScript/token-negotiator-gh-pages'
        user_email: ${{ secrets.USER_EMAIL_GITHUB }}
        user_name: ${{ secrets.USER_NAME_GITHUB }}
        target-branch: ci-cd-test
